### ISSUE TITLE
Can't find patient.h file

### ISSUE THREAD

**Issue by starsight** [cygnus718/HL7Parser#1]
Hello, Author. I cannot find patient.h file, so i cannot use Parser. If you have it, please upload this file. Thank you!

**Comment by rhajamor** [comment]
I think you can just deduce it from the cpp it would look like :

`class Patient{`
`public: `
`Patient(string name, string mrn, string dob, string address, string phone) ;`
`~Patient();`
`void displayPatientValues();`
`void savePatient();`
`bool checkDupePatient();`
`};`

**Comment by starsight** [comment]
Great! Thank You!
